### ISSUE TITLE
feat: add `spaceAroundHyperMark` rule

### ISSUE THREAD

**Issue by bingling-sama** [zhlint-project/zhlint#151]
如题，增加一个 `spaceAroundHyperMark` 规则，支持在 Markdown/HTML 标记周围添加空格，或者不去除 MD/HTML 标记周围的空格

**Comment by bingling-sama** [comment]
如果做成添加空格，要注意判断标签后紧邻的是否为中文标点

应为

> **注意**：


而不是

> **注意** ：

**Comment by Jinjiang** [comment]
@bingling-sama 抱歉拖了这么久才回复。

想进一步探讨一下需求，总体上我比较倾向于有没有 hyper mark 理论上需要判断的条件应该是相同的，除非遇到 markdown 解析的 bug (这种情况更多的要从 markdown parser 的层面去处理，zhlint 作为 markdown parser 的下游可以做的事情有限)。

举个例子，如果我们希望中英文之间有空格，那么：

`中文 **English**`、`**中文** English`、`中文 English` 都是正确的写法，而 `中文**English**`、`**中文**English`、`中文English` 则会被修正为之前的几个例子的格式

如果我没有猜错的话，你提到的例子其实是因为 markdown parser 的规则导致：

```
**注意**：中文

**注意：**中文
```

渲染结果：

**注意**：中文

**注意：**中文

后者会导致 markdown 渲染失败，所以有些人会加一个空格绕过这个问题

```
**注意：** 中文
```

渲染结果：

**注意：** 中文

如果我的猜测没有错的话，整件事情我觉得要分成两部分：

1. 解决 markdown 渲染问题：通常建议要么 `**注意**：中文`、要么索性用 HTML 标记 `<strong>注意</strong>：中文`。渲染结果：
    **注意**：中文
    <strong>注意</strong>：中文
2. 与其格式化 hyper mark 之外有或没有空格，我更倾向于格式化比如中英文之间有没有空格、逗号句号之类的结尾标点符号后有没有空格、成对的标点符号例如引号和括号外面有没有空格等。

谢谢

**Comment by bingling-sama** [comment]
也就是说 hyper mark 的样式不应该影响内容排版，那么目前的规则已经足够我们使用。此需求的出现是因为我们在排版时想将被 hyper mark 加粗 / 斜体化的内容与周围内容分割开，形成视觉上的强调效果。现在此需求已经不再重要，可以忽略此 Issue。
