### ISSUE TITLE
Can we support a vscode plugin?

### ISSUE THREAD

**Issue by xiantang** [zhlint-project/zhlint#47]
zhlint is awesome! but I also want use it in vscode to lint Zh, and it will be very powerful when we support it in vscode and use quick fix to correct Zh.

**Comment by KimYangOfCat** [comment]
附议，zhlint 的功能可能更适合作为一个编辑器插件

**Comment by action-hong** [comment]
糊了个粗糙的[版本](https://marketplace.visualstudio.com/items?itemName=kkopite.zhlint)，支持zhilint的错误提示、格式化以及配置，可以试用看看提下意见。

![zhlint](https://github.com/zhlint-project/zhlint/assets/16460309/2ec41889-ad89-4b61-b7f1-e6614e3b131e)

**Comment by Jinjiang** [comment]
@action-hong 赞👍
如果有兴趣的话，可以把项目 transfer 到这个 org 作为官方项目一起维护

**Comment by action-hong** [comment]
@Jinjiang 可以哈
