### ISSUE TITLE
英文整句情况下，换行前的标点符号也要求为全角符号

### ISSUE THREAD

**Issue by zhangsw** [zhlint-project/zhlint#60]
遇到英文整句且标点符号是当前行的最后一个字符时，当前规则下也要求使用全角符号。比如：
```
Blabla.
Haha.
```
check时 会要求`.`使用全角符号，这个和 https://github.com/sparanoid/chinese-copywriting-guidelines/blob/master/README.zh-Hans.md 以及其他的一些lint  检测规则冲突，这个是否需要优化下 ^_^

**Comment by yinan-c** [comment]
我也遇到了这个问题，处理英文单句的时候 `.` 被要求更改为全角句号，期待后续更新

**Comment by Jinjiang** [comment]
在计划中 #58 暂时可以给全英文的文本加 `<!-- zhlint disabled -->` 之类的 flag 跳过检查。🙏
